apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "api.name" . }}-php
  labels:
  {{- include "api.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": "pre-install,pre-upgrade"
    "helm.sh/hook-delete-policy": "before-hook-creation"
    "helm.sh/hook-weight": "0"
data:
  APP_ENV: {{ .Values.apache.appEnv | quote }}
  APP_DEBUG: {{ .Values.apache.appDebug | quote }}
  MAIL_MAILER: {{ .Values.apache.mailMailer | quote }}
  MAIL_HOST: {{ .Values.apache.mailHost | quote }}
  MAIL_PORT: {{ .Values.apache.mailPort | quote }}
  HASURA_BASE_URI: {{ tpl .Values.apache.hasuraBaseUri $ | quote }}
