apiVersion: v1
kind: Secret
metadata:
  name: {{ include "api.name" . }}-php
  labels:
  {{- include "api.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": "pre-install,pre-upgrade"
    "helm.sh/hook-delete-policy": "before-hook-creation"
    "helm.sh/hook-weight": "0"
type: Opaque
stringData:
  MAIL_USERNAME: {{ .Values.apache.mailUsername | quote }}
  MAIL_PASSWORD: {{ .Values.apache.mailPassword | quote }}
  HASURA_ADMIN_SECRET: {{ tpl .Values.apache.hasuraAdminSecret $ | quote }}
  APP_HASURA_SECRET: {{ .Values.apache.appHasuraSecret | quote }}
  APP_KEY: {{ .Values.apache.appKey | quote }}
{{- if .Values.postgresql.enabled }}
  DATABASE_URL: "postgresql://postgres:{{ .Values.postgresql.postgresqlPassword }}@{{ .Values.postgresql.fullnameOverride }}.{{ .Release.Namespace }}.svc.cluster.local/{{ .Values.postgresql.postgresqlDatabase }}"
{{- else }}
  DATABASE_URL: {{ .Values.postgresql.dbUrl | quote }}
{{- end }}
